version: '3.9'

services:
  app:
    restart: "no"
    build:
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=app.settings.docker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app/
    working_dir: /app
    depends_on:
      - db
      - redis
      
  db:
    image: postgres:15.6-alpine
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

